name: Deploy Standalone to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: psh/package-lock.json

      - name: Install Dependencies
        working-directory: psh
        run: npm ci

      - name: Build Next App
        working-directory: psh
        run: npm run build

      - name: Pack Runtime Files
        run: |
          cd psh
          FILES=".next server.js package.json package-lock.json public"
          tar -czf ../deploy.tar.gz $FILES

      - name: Upload to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "deploy.tar.gz"
          target: "/home/ubuntu/"

      - name: Restart Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            set -e

            rm -rf /home/ubuntu/psh
            mkdir /home/ubuntu/psh

            tar -xzf /home/ubuntu/deploy.tar.gz -C /home/ubuntu/psh
            rm -f /home/ubuntu/deploy.tar.gz

            cd /home/ubuntu/psh
            npm ci --omit=dev

            fuser -k 3000/tcp || true
            nohup node server.js > app.log 2>&1 &

            echo "Deploy Success!"
